# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ikimasho (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ikimasho (iOS)
pod 'lottie-ios'

end

target 'Ikimasho (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ikimasho (macOS)

end
